- name: Set up tmux
  hosts: localhost
  tasks:
    - name: Check for and/or install tmux
      community.general.pacman:
        name: tmux
      become: true
    - name: Create tmux folder
      ansible.builtin.file:
        name: "$HOME/.tmux/plugins/tpm"
        state: directory
    - name: Install tpm
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/tpm.git"
        dest: "~/.tmux/plugins/tpm"
    - name: Copy configuration
      ansible.builtin.copy:
        src: tmux.conf
        dest: ~/.tmux.conf
    - name: Get snazzy theme
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ivnvxd/tmux-snazzy/main/.tmux.snazzy.theme
        dest: ~/.tmux/tmux-snazzy.theme.conf
